### ISSUE TITLE
该教程如何在线阅读？

### ISSUE THREAD

**Issue by murphyzhao** [TencentCloudBase/handbook#1]
仓库里有看到教程，请问如何在线阅读？

Thanks

**Comment by ppambler** [comment]
@murphyzhao 

小程序开发入门 ：https://tencentcloudbase.github.io/handbook/tcb01.html

JS入门：https://tencentcloudbase.github.io/handbook/tcb11.html

云开发快速入门：https://tencentcloudbase.github.io/handbook/tcb21.html

**Comment by murphyzhao** [comment]
> @murphyzhao
> 
> 小程序开发入门 ：https://tencentcloudbase.github.io/handbook/tcb01.html
> 
> JS入门：https://tencentcloudbase.github.io/handbook/tcb11.html
> 
> 云开发快速入门：https://tencentcloudbase.github.io/handbook/tcb21.html

好的，thanks
